my_list = [5, 3, 8, 1, 2, 7]
print("Type of my_list:", type(my_list))
my_list.append(4)
print("After append:", my_list)
my_list.insert(2, 6)
print("After insert:", my_list)
my_list.remove(8)
print("After remove:", my_list)
popped_element = my_list.pop(3)
print("Popped Element:", popped_element)
print("After pop:", my_list)
my_list.clear()
print("After clear:", my_list)
my_list = [5, 3, 8, 1, 2, 7]
my_list.sort()
print("After sort:", my_list)
length = len(my_list)
print("Length of list:", length)
my_list.reverse()
print("After reverse:", my_list)
minimum = min(my_list)
print("Minimum value:", minimum)
maximum = max(my_list)
print("Maximum value:", maximum)
count = my_list.count(3)
print("Count of 3:", count)
total_sum = sum(my_list)
print("Sum of list:", total_sum)
index = my_list.index(2)
print("Index of 2:", index)
